# Generated by Django 5.2.4 on 2025-08-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        # Drop the existing Vote table to fix the voter_id column type issue
        migrations.RunSQL(
            "DROP TABLE IF EXISTS polls_vote CASCADE;",
            reverse_sql="-- This migration cannot be reversed automatically"
        ),
        # Recreate the Vote table with correct schema
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.option')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'indexes': [models.Index(fields=['voter', 'option'], name='polls_vote_voter_i_5bbfa0_idx')],
                'unique_together': {('option', 'voter')},
            },
        ),
    ]
